### ISSUE TITLE
500 Error on babka.social

### ISSUE THREAD

**Issue by ChaplainRunbox** [fenwick67/mastofeed#70] opened 2024-06-13 14:09 UTC
I am getting an error 500 message ~ thanks for any help.

Sorry, we are having trouble fetching posts for this user. Please try again later.

If the issue persists, [please open an issue on GitHub](https://github.com/fenwick67/mastofeed/issues), or message fenwick67@octodon.social

**Comment by fenwick67** [comment] 2024-10-13 03:25
confirmed duplicate of #41

**Closed as completed by fenwick67** 2024-10-13 03:25 UTC
