### ISSUE TITLE
500 fetch error

### ISSUE THREAD

**Issue by ColumbiaView** [fenwick67/mastofeed#61] opened 2023-10-11 15:01 UTC
Hello. 

This error (500 error "Sorry, we are having trouble fetching posts for this user. Please try again later.") has been happening to me for the past few days. I can get to my profile at https://climatejustice.rocks/@CascadiaCAN but the feeds to my webs e.g. https://sallykeely.com/ have one Mastodon feed no longer works (the other two do). Can you help me troubleshoot this please? 

~Sally 

PS. This may be related to the closed issue #41.

**Comment by sfroemkenjw** [comment] 2023-12-01 07:38
Today I had the same problem. But in generated URI I saw that `https://` was inserted duplicated. So I have removed the scheme `https://´ from instance URL and it works for me now.

**Comment by ColumbiaView** [comment] 2023-12-01 19:59
@sfroemkenjw Thanks for the suggestion. Unfortunately that didn't fix the 500 error for me, e.g. at https://sallykeely.com/test.html. The feed works fine for me for other instances, but not for the instance climatejustice.rocks.

**Comment by paulo-roger** [comment] 2023-12-26 15:19
> https://climatejustice.rocks/@CascadiaCAN

![](https://i.imgur.com/ludFkfU.png)

**Comment by FediVideos** [comment] 2024-04-15 16:21
Same problem for accounts on social.growyourown.services and social.chinwag.org, 500 error every time. Is this possibly related to authorized fetch being switched on, as both of these use it?

**Comment by fenwick67** [comment] 2024-10-13 03:24
this one confirmed duplicate of #41

**Closed as completed by fenwick67** 2024-10-13 03:24 UTC
