### ISSUE TITLE
Internal Server Error when querying BotsInSpace

### ISSUE THREAD

**Issue by avia-tion-ca** [fenwick67/mastofeed#56] opened 2023-08-08 15:02 UTC
"[500](https://mastofeed.com/apiv2/feed?userurl=https%3A%2F%2Fbotsin.space%2Fusers%2Fsosaglidingbot&theme=light&size=75&header=false&replies=true&boosts=true#)

Sorry, we are having trouble fetching posts for this user. Please try again later.

If the issue persists, [please open an issue on GitHub](https://github.com/fenwick67/mastofeed/issues), or message fenwick67"

Error appears with:
https://mastofeed.com/apiv2/feed?userurl=https%3A%2F%2Fbotsin.space%2Fusers%2Fsosaglidingbot&theme=light&size=75&header=false&replies=true&boosts=true

Error does not appear with:
https://mastofeed.com/apiv2/feed?userurl=https%3A%2F%2Faircrew.rocks%2Fusers%2Fsosaglidingclub&theme=light&size=75&header=false&replies=true&boosts=true

**Comment by fenwick67** [comment] 2023-08-26 02:35
I'm gonna guess this is a duplicate of #41

**Closed as not planned by fenwick67** 2023-08-26 02:35 UTC
